package com.softdesign.devintensive.utils;


public interface ConstantManager {
    String TAG_PREFIX = "DEV";
    String EDIT_MODE_KEY = "EDIT_MODE_KEY";

    String USER_PHONE_KEY = "USER_PHONE_KEY";
    String USER_MAIL_KEY = "USER_MAIL_KEY";
    String USER_VK_KEY = "USER_VK_KEY";
    String USER_GIT_KEY = "USER_GIT_KEY";
    String USER_BIO_KEY = "USER_BIO_KEY";
    String USER_PHOTO_KEY = "USER_PHOTO_KEY";
    String USER_AVATAR_KEY = "USER_AVATAR_KEY";
    String AUTH_TOKEN = "AUTH_TOKEN";
    String USER_ID_KEY = "USER_ID_KEY";

    String USER_RAITING_VALUE = "USER_RAITING_VALUE";
    String USER_CODE_LINES_NUM_VALUE = "USER_CODE_LINES_NUM_VALUE";
    String USER_PROJECTS_NUM_VALUE = "USER_PROJECTS_NUM_VALUE";

    String USER_FIRST_NAME_KEY = "USER_FIRST_NAME_KEY";
    String USER_SECOND_NAME_KEY = "USER_SECOND_NAME_KEY";

    int LOAD_PROFILE_PHOTO_DIALOG = 1;
    int REQUEST_CAMERA_PICTURE = 47;
    int REQUEST_GALLERY_PICTURE = 48;
    int PERMISSION_REQUEST_SETTINGS_CODE = 49;
    int CAMERA_REQUEST_PERMISSIONS_CODE = 50;
    int CALL_PHONE_PERMISSIONS_CODE = 51;

}
